version: "3.8"

networks:
    frontend:
        external: true
        name: frontend


services:
    api:
      image: swatipanwar/test_api_dev:latest
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=frontend"
            - "traefik.port=80:80"
            - "traefik.port=80"

            - "traefik.http.routers.api.rule=Host(`api.localhost`) && PathPrefix(`${MOUNTPOINT:/testapi`)"
            - "traefik.http.routers.api.tls=true"
            - "traefik.http.routers.api.entrypoints=websecure"
